version: "3.7"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    ports:
      - "5000:5000"
    environment:
      - MONGODB_URI=mongodb+srv://sai:1234@cluster0.3xjhj7c.mongodb.net/expenditureapp
    depends_on:
      - mongo

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_cont:/data/db

volumes:
  mongodb_data_cont: